/* Site-wide keyword search for the guide pages.
 * Self-contained: injects its own CSS and DOM. Include with:
 *   <script src="./search.js" defer></script>
 * Loads ./search-index.json (generated by scripts/generate_search_index.py).
 * Shortcuts: Ctrl+K / Cmd+K or "/" opens the search box, Esc closes it.
 */
(function () {
  'use strict';

  /* ---------------- CSS ---------------- */
  var css = `
.search-btn {
  margin-left: auto;
  display: inline-flex; align-items: center; gap: 6px;
  padding: 5px 12px; border-radius: 8px;
  border: 1px solid var(--line); background: var(--bg);
  color: var(--muted); font-size: 13px; cursor: pointer;
  white-space: nowrap; transition: border-color .15s, color .15s;
}
.search-btn:hover { border-color: var(--accent); color: var(--accent); }
.search-btn kbd {
  font-family: inherit; font-size: 11px; color: var(--muted);
  border: 1px solid var(--line); border-radius: 4px; padding: 0 5px;
  background: var(--surface);
}
.search-overlay {
  position: fixed; inset: 0; z-index: 2000;
  background: rgba(15, 23, 42, 0.45);
  display: flex; align-items: flex-start; justify-content: center;
  padding-top: 12vh;
  opacity: 0; visibility: hidden;
  transition: opacity .18s ease, visibility .18s ease;
}
.search-overlay.active { opacity: 1; visibility: visible; }
.search-modal {
  width: min(640px, 92vw); max-height: 70vh;
  display: flex; flex-direction: column;
  background: var(--surface); color: var(--text);
  border: 1px solid var(--line); border-radius: 14px;
  box-shadow: 0 20px 60px rgba(0,0,0,0.25);
  overflow: hidden;
}
.search-input-row {
  display: flex; align-items: center; gap: 10px;
  padding: 14px 16px; border-bottom: 1px solid var(--line);
}
.search-input-row svg { flex-shrink: 0; color: var(--muted); }
#search-input {
  flex: 1; border: none; outline: none; background: transparent;
  color: var(--text); font-size: 16px; font-family: inherit;
}
#search-input::placeholder { color: var(--muted); }
.search-kbd-hint {
  font-size: 11px; color: var(--muted);
  border: 1px solid var(--line); border-radius: 4px; padding: 1px 6px;
  white-space: nowrap;
}
.search-results { overflow-y: auto; padding: 8px; }
.search-empty { padding: 28px 16px; text-align: center; color: var(--muted); font-size: 14px; }
.search-item {
  display: block; width: 100%; text-align: left;
  padding: 10px 12px; border: none; border-radius: 10px;
  background: transparent; color: var(--text); cursor: pointer;
  font-family: inherit;
}
.search-item:hover, .search-item.selected { background: var(--accent-soft); }
.search-item .si-page {
  font-size: 12px; color: var(--accent); font-weight: 700;
  margin-bottom: 2px;
}
.search-item .si-title { font-size: 14.5px; font-weight: 600; line-height: 1.4; }
.search-item .si-snippet {
  font-size: 12.5px; color: var(--muted); line-height: 1.5; margin-top: 2px;
  display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden;
}
.search-item mark {
  background: #fde68a; color: #78350f; border-radius: 2px; padding: 0 1px;
}
@media (prefers-color-scheme: dark) {
  .search-item mark { background: #854d0e; color: #fde68a; }
}
/* Breathing highlight for the jump target section (~5s). */
@keyframes searchBreath {
  0%, 100% { background-color: rgba(219, 39, 119, 0); }
  50% { background-color: rgba(219, 39, 119, 0.16); }
}
.search-breath {
  animation: searchBreath 1s ease-in-out 5;
  border-radius: 8px;
}
.search-footer {
  padding: 8px 16px; border-top: 1px solid var(--line);
  font-size: 11.5px; color: var(--muted);
  display: flex; gap: 14px;
}
`;

  /* ---------------- DOM ---------------- */
  function inject() {
    var style = document.createElement('style');
    style.textContent = css;
    document.head.appendChild(style);

    var navbar = document.querySelector('.navbar-inner');
    if (!navbar) return;

    var btn = document.createElement('button');
    btn.className = 'search-btn';
    btn.type = 'button';
    btn.innerHTML = '<span>搜索</span><kbd>Ctrl K</kbd>';
    btn.addEventListener('click', openSearch);
    navbar.appendChild(btn);

    var overlay = document.createElement('div');
    overlay.className = 'search-overlay';
    overlay.innerHTML =
      '<div class="search-modal">' +
        '<div class="search-input-row">' +
          '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>' +
          '<input id="search-input" type="text" placeholder="输入关键字检索全部页面…" autocomplete="off">' +
          '<span class="search-kbd-hint">Esc 关闭</span>' +
        '</div>' +
        '<div class="search-results" id="search-results"></div>' +
        '<div class="search-footer"><span>↑↓ 选择</span><span>Enter 跳转</span><span>Esc 关闭</span></div>' +
      '</div>';
    document.body.appendChild(overlay);

    overlay.addEventListener('click', function (e) {
      if (e.target === overlay) closeSearch();
    });

    var input = overlay.querySelector('#search-input');
    input.addEventListener('input', function () { render(this.value); });
    input.addEventListener('keydown', onInputKey);
  }

  /* ---------------- State ---------------- */
  var INDEX = null;
  var overlayEl, inputEl, resultsEl;
  var items = [];
  var selected = -1;
  var breathNodes = null;
  var breathTimer = null;

  /* ---------------- Last search memory (localStorage) ---------------- */
  var STORE_KEY = 'guide-search-state';

  function saveState() {
    try {
      var it = (selected >= 0 && items[selected]) ? items[selected] : null;
      localStorage.setItem(STORE_KEY, JSON.stringify({
        keyword: inputEl ? inputEl.value : '',
        page: it ? it.page : '',
        id: it ? it.id : ''
      }));
    } catch (e) { /* storage unavailable */ }
  }

  function loadState() {
    try {
      var raw = localStorage.getItem(STORE_KEY);
      return raw ? JSON.parse(raw) : null;
    } catch (e) { return null; }
  }

  function loadIndex() {
    if (INDEX) return Promise.resolve(INDEX);
    return fetch('./search-index.json')
      .then(function (r) { return r.json(); })
      .then(function (data) { INDEX = data; return data; })
      .catch(function () { INDEX = []; return []; });
  }

  function openSearch() {
    overlayEl = document.querySelector('.search-overlay');
    inputEl = overlayEl.querySelector('#search-input');
    resultsEl = overlayEl.querySelector('#search-results');
    overlayEl.classList.add('active');
    document.body.style.overflow = 'hidden';
    // Restore last keyword so the user can continue where they left off.
    var state = loadState();
    if (state && state.keyword && !inputEl.value) {
      inputEl.value = state.keyword;
    }
    loadIndex().then(function () {
      render(inputEl.value);
      // Restore last selected item by page + section id (robust to index changes).
      if (state && state.keyword === inputEl.value && (state.page || state.id)) {
        for (var i = 0; i < items.length; i++) {
          if (items[i].page === state.page && items[i].id === state.id) {
            selectItem(i);
            scrollSelectedIntoView();
            break;
          }
        }
      }
    });
    setTimeout(function () { inputEl.focus(); inputEl.select(); }, 30);
  }

  function closeSearch() {
    if (!overlayEl) return;
    overlayEl.classList.remove('active');
    document.body.style.overflow = '';
    selected = -1;
  }

  /* ---------------- Search ---------------- */
  function escapeHtml(s) {
    return s.replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function escapeRegExp(s) {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  function highlight(text, keywords) {
    var out = escapeHtml(text);
    keywords.forEach(function (k) {
      if (!k) return;
      out = out.replace(new RegExp('(' + escapeRegExp(escapeHtml(k)) + ')', 'gi'), '<mark>$1</mark>');
    });
    return out;
  }

  function makeSnippet(text, keywords) {
    if (!text) return '';
    var pos = -1, kw = '';
    var lower = text.toLowerCase();
    keywords.forEach(function (k) {
      var p = lower.indexOf(k.toLowerCase());
      if (p !== -1 && (pos === -1 || p < pos)) { pos = p; kw = k; }
    });
    if (pos === -1) return text.slice(0, 120);
    var start = Math.max(0, pos - 50);
    var end = Math.min(text.length, pos + kw.length + 80);
    return (start > 0 ? '…' : '') + text.slice(start, end) + (end < text.length ? '…' : '');
  }

  function search(keyword) {
    var keywords = keyword.trim().split(/\s+/).filter(Boolean);
    if (!keywords.length) return [];
    var results = [];
    INDEX.forEach(function (page) {
      // page-level match (page title)
      var pageTitleHit = keywords.every(function (k) {
        return page.pageTitle.toLowerCase().indexOf(k.toLowerCase()) !== -1;
      });
      page.sections.forEach(function (sec) {
        var hayTitle = sec.title.toLowerCase();
        var hayText = sec.text.toLowerCase();
        var inTitle = keywords.every(function (k) { return hayTitle.indexOf(k.toLowerCase()) !== -1; });
        var inText = keywords.every(function (k) { return hayText.indexOf(k.toLowerCase()) !== -1; });
        var inPage = pageTitleHit;
        if (inTitle || inText || inPage) {
          results.push({
            page: page.page,
            pageTitle: page.pageTitle,
            id: sec.id,
            title: sec.title,
            snippet: makeSnippet(sec.text, keywords),
            score: inTitle ? 0 : (inText ? 1 : 2)
          });
        }
      });
      // page with no sections: still allow page-level jump
      if (!page.sections.length && pageTitleHit) {
        results.push({
          page: page.page, pageTitle: page.pageTitle, id: '',
          title: page.pageTitle, snippet: '', score: 1
        });
      }
    });
    results.sort(function (a, b) { return a.score - b.score; });
    return results.slice(0, 30);
  }

  function render(keyword) {
    if (!resultsEl) return;
    var keywords = keyword.trim().split(/\s+/).filter(Boolean);
    if (!keywords.length) {
      resultsEl.innerHTML = '<div class="search-empty">输入关键字开始检索（支持空格分隔多个关键字）</div>';
      items = []; selected = -1;
      return;
    }
    items = search(keyword);
    selected = items.length ? 0 : -1;
    if (!items.length) {
      resultsEl.innerHTML = '<div class="search-empty">没有找到「' + escapeHtml(keyword) + '」相关内容</div>';
      return;
    }
    resultsEl.innerHTML = items.map(function (it, i) {
      return '<button type="button" class="search-item' + (i === selected ? ' selected' : '') + '" data-i="' + i + '">' +
        '<div class="si-page">' + escapeHtml(it.pageTitle) + '</div>' +
        '<div class="si-title">' + highlight(it.title, keywords) + '</div>' +
        (it.snippet ? '<div class="si-snippet">' + highlight(it.snippet, keywords) + '</div>' : '') +
      '</button>';
    }).join('');
    Array.prototype.forEach.call(resultsEl.querySelectorAll('.search-item'), function (el) {
      el.addEventListener('click', function () { go(parseInt(el.getAttribute('data-i'), 10)); });
      el.addEventListener('mousemove', function () { selectItem(parseInt(el.getAttribute('data-i'), 10)); });
    });
    resultsEl.scrollTop = 0;
    saveState();
  }

  function selectItem(i) {
    if (i === selected) return;
    selected = i;
    Array.prototype.forEach.call(resultsEl.querySelectorAll('.search-item'), function (el, j) {
      el.classList.toggle('selected', j === i);
    });
    saveState();
  }

  function scrollSelectedIntoView() {
    var el = resultsEl.querySelector('.search-item.selected');
    if (el) el.scrollIntoView({ block: 'nearest' });
  }

  function onInputKey(e) {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (items.length) { selectItem(Math.min(selected + 1, items.length - 1)); scrollSelectedIntoView(); }
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      if (items.length) { selectItem(Math.max(selected - 1, 0)); scrollSelectedIntoView(); }
    } else if (e.key === 'Enter') {
      e.preventDefault();
      if (selected >= 0) go(selected);
    }
  }

  function go(i) {
    var it = items[i];
    if (!it) return;
    saveState();
    var current = location.pathname.split('/').pop() || 'index.html';
    var target = it.page;
    var hash = it.id ? '#' + it.id : '';
    if (target === current) {
      closeSearch();
      if (it.id) {
        var el = document.getElementById(it.id);
        if (el) {
          history.replaceState(null, '', hash);
          el.scrollIntoView({ behavior: 'smooth', block: 'start' });
          flashHighlight(el);
        }
      }
    } else {
      location.href = './' + target + hash;
    }
  }

  /* Breathing highlight: cover the whole section under the target heading
   * (the heading itself plus every sibling until the next same-or-higher
   * level heading), pulsing for ~5 seconds. */
  function flashHighlight(el) {
    clearBreath();
    var stopLevel = parseInt(el.tagName.slice(1), 10) || 2;
    var nodes = [el];
    var n = el.nextElementSibling;
    while (n) {
      if (/^H[1-6]$/.test(n.tagName) && parseInt(n.tagName.slice(1), 10) <= stopLevel) break;
      nodes.push(n);
      n = n.nextElementSibling;
    }
    breathNodes = nodes;
    nodes.forEach(function (node) { node.classList.add('search-breath'); });
    breathTimer = setTimeout(clearBreath, 5100);
  }

  function clearBreath() {
    if (breathTimer) { clearTimeout(breathTimer); breathTimer = null; }
    if (breathNodes) {
      breathNodes.forEach(function (node) { node.classList.remove('search-breath'); });
      breathNodes = null;
    }
  }

  /* ---------------- Shortcuts ---------------- */
  document.addEventListener('keydown', function (e) {
    var tag = (e.target.tagName || '').toLowerCase();
    var typing = tag === 'input' || tag === 'textarea' || e.target.isContentEditable;
    if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') {
      e.preventDefault();
      openSearch();
    } else if (e.key === '/' && !typing) {
      e.preventDefault();
      openSearch();
    } else if (e.key === 'Escape') {
      closeSearch();
    }
  });

  /* ---------------- Boot ---------------- */
  // On landing with a #sec-N hash (from a cross-page jump), flash the target.
  window.addEventListener('load', function () {
    if (location.hash) {
      var el = document.getElementById(location.hash.slice(1));
      if (el) setTimeout(function () { flashHighlight(el); }, 400);
    }
  });

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', inject);
  } else {
    inject();
  }
})();
